RD bin /S /Q
RD obj /S /Q
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile2 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile102 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile104 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile95 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile136 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile14 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile143 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile147 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile154 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile158 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile18 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile19 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile225 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile23 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile24 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile240 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile255 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile3 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile328 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile336 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile344 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile36 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile37 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile4 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile41 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile42 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile46 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile47 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile5 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile6 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile88 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile92 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile96 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile111 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile259 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile49 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile7 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile78 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile151 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile157 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile31 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile32 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile44 Toe.Math.csproj
msbuild.exe /property:Platform=AnyCPU /property:Configuration=Profile84 Toe.Math.csproj
..\packages\NuGet.CommandLine.2.8.3\tools\NuGet.exe pack Toe.Math.csproj.nuspec -Prop Configuration=Release -BasePath .\ -OutputDirectory ..\nuget